image: alpine

pages:
  script:
  - pip install sphinx python-dev py2-pip
  - apk --no-cache add make
  - cd docs
  - make html
  - cd ..
  - mv docs/_build/html/ public/
  artifacts:
    paths:
    - public
