image: pytorch/pytorch:latest

pytest:
  stage: test
  script:
  - apk --no-cache add py3-pip python3-dev make automake g++
  - pip install pytest .
  - pytest --junitxml=report.xml
  artifacts:
    reports:
      junit: report.xml


image: alpine

pages:
  stage: deploy
  script:
  - apk --no-cache add py3-pip python3-dev make
  - pip install sphinx m2r2 sphinx-rtd-theme sphinxcontrib-bibtex
  - cd docs
  - make html
  - cd ..
  - mv docs/_build/html/ public/
  artifacts:
    paths:
    - public
