pytest:
  image: continuumio/miniconda3
  stage: test
  script:
  - conda update -n base 
  - conda install numba pip
  - pip install pytest .[all]
  - pytest --junitxml=report.xml
  artifacts:
    reports:
      junit: report.xml

pages:
  image: alpine
  stage: deploy
  script:
  - apk add py3-pip python3-dev make
  - pip install sphinx m2r2 sphinx-rtd-theme sphinxcontrib-bibtex
  - cd docs
  - make html
  - cd ..
  - mv docs/_build/html/ public/
  artifacts:
    paths:
    - public
 