image: alpine

pages:
  script:
  - apk --no-cache add py3-pip python3-dev
  - pip install sphinx m2r2
  - sphinx-apidoc -f -T -o docs medil
  - mv docs/medil.rst docs/documentation.rst
  - apk --no-cache add make
  - cd docs
  - make html
  - cd ..
  - mv docs/_build/html/ public/
  artifacts:
    paths:
    - public
