image: pytorchlightning/pytorch_lightning:latest-py3.7-torch1.4

pytest:
  stage: test
  script:
  - apk --no-cache add py3-pip py3-scipy py3-matplotlib
  - pip install pytest .[all]
  - pytest --junitxml=report.xml
  artifacts:
    reports:
      junit: report.xml


image: alpine

pages:
  stage: deploy
  script:
  - apk --no-cache add py3-pip python3-dev make
  - pip install sphinx m2r2 sphinx-rtd-theme sphinxcontrib-bibtex
  - cd docs
  - make html
  - cd ..
  - mv docs/_build/html/ public/
  artifacts:
    paths:
    - public
