pytest:
  image: continuumio/miniconda3
  stage: test
  only:
    - merge_requests
    - main
  script:
    - conda update conda
    - conda install pip
    - pip install pytest-cov .[all]
    - python -m pytest --cov-report html --cov-report term --cov=medil
  artifacts:
    paths:
      - htmlcov/

pages:
  image: alpine
  stage: deploy
  only:
    - merge_requests
    - main
  script:
    - apk add py3-pip python3-dev make unzip
    - pip install sphinx m2r2 sphinx-rtd-theme sphinxcontrib-bibtex
    - cd docs
    - make html
    - cd ..
    - mv docs/_build/html/ public/
    - wget https://gitlab.com/alex-markham/medil/-/jobs/artifacts/develop/download?job=pytest
    - unzip -o 'download?job=pytest'
    - mv htmlcov/ public/
  artifacts:
    paths:
    - public
