# pytest:
#   image: continuumio/miniconda3
#   stage: test
#   script:
#     - conda update conda
#     - conda install pip
#     - pip install pytest-cov .[all]
#     - python -m pytest --cov-report html --cov-report term --cov=medil --ignore=tests/test_functional_MCM.py --ignore=tests/test_heuristic.py
#   artifacts:
#     paths:
#       - htmlcov/

pages:
  image: alpine
  stage: deploy
  script:
    - apk add py3-pip python3-dev make unzip pandoc-cli
    - pip install 'sphinx<7' m2r2 sphinx-rtd-theme sphinxcontrib-bibtex
    - cd docs
    - pandoc -s ../CHANGELOG.md -o changelog.rst
    - make html
    - cd ..
    - mv docs/_build/html/ public/
    # - wget https://gitlab.com/alex-markham/medil/-/jobs/artifacts/develop/download?job=pytest
    # - unzip -o 'download?job=pytest'
    # - mv htmlcov/ public/
  artifacts:
    paths:
    - public
