# pytest:
#   image: continuumio/miniconda3
#   stage: test
#   script:
#     - conda update conda
#     - conda install pip
#     - pip install pytest-cov .
#     - python -m pytest --cov-report html --cov-report term --cov=medil
#   artifacts:
#     paths:
#       - htmlcov/

pages:
  image: alpine
  stage: deploy
  script:
    - apk add make curl unzip py3-pip python3-dev
    - python3 -m venv .
    - . bin/activate
    - pip install setuptools sphinx sphinx-rtd-theme sphinx-mdinclude sphinxcontrib-bibtex
    - cd docs
    - make html
    - cd ..
    - mv docs/_build/html/ public/
    - ls
    - 'curl --location --output artifacts.zip "https://gitlab.com/projects/$CI_PROJECT_ID/jobs/artifacts/develop/download?job=pytest&job_token=$CI_JOB_TOKEN"'
    - ls
    - unzip artifacts.zip
    - mv htmlcov/ public/
  artifacts:
    paths:
    - public
