pytest:
  image: continuumio/miniconda3
  stage: test
  script:
  - conda update conda
  - conda install numba pip
  - pip install pytest-cov .[all]
  - python -m pytest --cov-report html --cov-report term --cov=medil
  artifacts:
    paths:
      - htmlcov/

pages:
  image: alpine
  stage: deploy
  dependencies:
  - pytest
  script:
  - apk add py3-pip python3-dev make
  - pip install sphinx m2r2 sphinx-rtd-theme sphinxcontrib-bibtex
  - cd docs
  - make html
  - cd ..
  - mv docs/_build/html/ public/
  - mv htmlcov/ public/_static/
  artifacts:
    paths:
    - public
 