pytest:
  image: continuumio/miniconda3
  stage: test
  script:
  - conda update conda
  - conda install numba pip
  - pip install pytest-cov .[all]
  - python -m pytest --cov=medil
  artifacts:
    reports:
      - coverage.xml

pages:
  image: alpine
  stage: deploy
  script:
  - apk add py3-pip python3-dev make
  - pip install sphinx m2r2 sphinx-rtd-theme sphinxcontrib-bibtex
  - cd docs
  - make html
  - cd ..
  - mv docs/_build/html/ public/
  artifacts:
    paths:
    - public
 